on: push
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        
      - name: Display Node.js version
        run: node --version

      - name: Display npm version
        run: npm --version
